name: myst
description: The simple flutter structure cli which can help you to be more productive
version: 0.0.1+1
homepage: https://github.com/kechankrisna/myst

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies: 
  args: ^2.3.0
  cli_util: ^0.3.5
  os_detect: ^2.0.0
  path: ^1.8.0
  printx: ^0.0.1
  process: ^4.2.4
  process_run: ^0.12.3+2
  recase: ^4.0.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0


executables:
  myst: myst