name: adaptivex
description: This package allow you to build the widget based on width (screen) size or platform
version: 0.0.1+3
homepage: https://github.com/kechankrisna/myst

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^1.0.0
  flutter_test:
    sdk: flutter
