name: adaptivex
description: This package allow you to build the widget based on width (screen) size or platform
version: 0.0.1+5
homepage: https://github.com/kechankrisna/myst/tree/main/packages/adaptivex

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  printx: ^0.0.1

dev_dependencies:
  lints: ^1.0.0
  flutter_test:
    sdk: flutter
